apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-manifest-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fontbakery-manifest-master
        role: manifest
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: fontbakery-manifest-master
        image: gcr.io/fontbakery-168509/base-javascript:4
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: RETHINKDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: rethinkdb-password
        workingDir: /var/javascript
        command: ["node", "node/ManifestMaster.js"]
