apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-reports
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fontbakery-reports
        role: reportsserver
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: fontbakery-reports
        image: gcr.io/fontbakery-168509/base-javascript:5
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
          - name: RETHINKDB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: external-resources
                key: rethinkdb-password
        ports:
        - containerPort: 50051
        workingDir: /var/javascript
        command: ["node", "node/ReportsServer.js", "-p", "50051"]
        # command: ["node", "--inspect=0.0.0.0:9229", "node/ReportsServer.js", "-p", "50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-reports
  labels:
    component: fontbakery-reports
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-reports
    role: reportsserver
