apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-storage-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fontbakery-storage-cache
        role: messagecache
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: fontbakery-storage-cache
        image: gcr.io/fontbakery-168509/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
        ports:
        - containerPort: 50051
        resources:
          limits:
            cpu: 1
            memory: 5Gi
          requests:
            cpu: .5
            memory: 2Gi
        workingDir: /var/javascript
        command: ["node", "node/CacheServer.js", "-p", "50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-storage-cache
  labels:
    component: fontbakery-storage-cache
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-storage-cache
    role: messagecache
