apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: fontbakery-worker-distributor
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: fontbakery-worker-distributor
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
      - name: fontbakery-worker-distributor
        image: gcr.io/fontbakery-168509/base-python:32
        workingDir: /var/python
        command: ["python3",  "-u", "fontbakery-worker-distributor.py"]
