apiVersion: apps/v1beta1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: fontbakery-storage-cache
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: fontbakery-storage-cache
        role: messagecache
    spec:
      containers:
      - name: fontbakery-storage-cache
        image: fontbakery/base-javascript:1
        env:
          - name: FONTBAKERY_LOG_LEVEL
            value: "DEBUG"
        ports:
        - containerPort: 50051
        workingDir: /var/javascript
        command: ["node", "node/CacheServer.js", "-p", "50051"]
---
apiVersion: v1
kind: Service
metadata:
  name: fontbakery-storage-cache
  labels:
    component: fontbakery-storage-cache
spec:
  ports:
    - port: 50051
      targetPort: 50051
  selector:
    component: fontbakery-storage-cache
    role: messagecache
